NDefines.NTechnology.IDEAL_YEAR_LEVEL_0 = 2375
NDefines.NTechnology.IDEAL_YEAR_LEVEL_8 = 3200
NDefines.NTechnology.DONT_EXECUTE_TECH_BEFORE = 2555
NDefines.NEngine.MISSING_SCRIPTED_SUCCESSOR_ERROR_CUTOFF_YEAR = 2570
